// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance.Database.Models;

namespace Persistance.Database.Migrations
{
    [DbContext(typeof(PizzeriaDbContext))]
    partial class PizzeriaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Persistance.Database.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("apellido")
                        .HasColumnType("int");

                    b.Property<int>("nombre")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Persistance.Database.Models.DetallePedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Pedidoid")
                        .HasColumnType("int");

                    b.Property<int>("montoUnitario")
                        .HasColumnType("int");

                    b.Property<int?>("pizzaid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Pedidoid");

                    b.HasIndex("pizzaid");

                    b.ToTable("Detalle");
                });

            modelBuilder.Entity("Persistance.Database.Models.Estado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ambito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descipcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("Persistance.Database.Models.Factura", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("monto")
                        .HasColumnType("int");

                    b.Property<int?>("pedidoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("pedidoid");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("Persistance.Database.Models.Ingrediente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Variedadid")
                        .HasColumnType("int");

                    b.Property<string>("descipcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Variedadid");

                    b.ToTable("Ingrediente");
                });

            modelBuilder.Entity("Persistance.Database.Models.Menu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("Persistance.Database.Models.Pedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("clienteid")
                        .HasColumnType("int");

                    b.Property<int?>("estadoid")
                        .HasColumnType("int");

                    b.Property<int>("total")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("clienteid");

                    b.HasIndex("estadoid");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Persistance.Database.Models.Pizza", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Menuid")
                        .HasColumnType("int");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.Property<int?>("tamañoid")
                        .HasColumnType("int");

                    b.Property<int?>("tipoPizzaid")
                        .HasColumnType("int");

                    b.Property<int?>("variedadid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Menuid");

                    b.HasIndex("tamañoid");

                    b.HasIndex("tipoPizzaid");

                    b.HasIndex("variedadid");

                    b.ToTable("Pizza");
                });

            modelBuilder.Entity("Persistance.Database.Models.Tamaño", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("porciones")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Tamaño");
                });

            modelBuilder.Entity("Persistance.Database.Models.TipoPizza", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TipoPizza");
                });

            modelBuilder.Entity("Persistance.Database.Models.Variedad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("descripcion")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Variedad");
                });

            modelBuilder.Entity("Persistance.Database.Models.DetallePedido", b =>
                {
                    b.HasOne("Persistance.Database.Models.Pedido", null)
                        .WithMany("detalles")
                        .HasForeignKey("Pedidoid");

                    b.HasOne("Persistance.Database.Models.Pizza", "pizza")
                        .WithMany()
                        .HasForeignKey("pizzaid");

                    b.Navigation("pizza");
                });

            modelBuilder.Entity("Persistance.Database.Models.Factura", b =>
                {
                    b.HasOne("Persistance.Database.Models.Pedido", "pedido")
                        .WithMany()
                        .HasForeignKey("pedidoid");

                    b.Navigation("pedido");
                });

            modelBuilder.Entity("Persistance.Database.Models.Ingrediente", b =>
                {
                    b.HasOne("Persistance.Database.Models.Variedad", null)
                        .WithMany("ingredientes")
                        .HasForeignKey("Variedadid");
                });

            modelBuilder.Entity("Persistance.Database.Models.Pedido", b =>
                {
                    b.HasOne("Persistance.Database.Models.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteid");

                    b.HasOne("Persistance.Database.Models.Estado", "estado")
                        .WithMany()
                        .HasForeignKey("estadoid");

                    b.Navigation("cliente");

                    b.Navigation("estado");
                });

            modelBuilder.Entity("Persistance.Database.Models.Pizza", b =>
                {
                    b.HasOne("Persistance.Database.Models.Menu", null)
                        .WithMany("pizzas")
                        .HasForeignKey("Menuid");

                    b.HasOne("Persistance.Database.Models.Tamaño", "tamaño")
                        .WithMany()
                        .HasForeignKey("tamañoid");

                    b.HasOne("Persistance.Database.Models.TipoPizza", "tipoPizza")
                        .WithMany()
                        .HasForeignKey("tipoPizzaid");

                    b.HasOne("Persistance.Database.Models.Variedad", "variedad")
                        .WithMany()
                        .HasForeignKey("variedadid");

                    b.Navigation("tamaño");

                    b.Navigation("tipoPizza");

                    b.Navigation("variedad");
                });

            modelBuilder.Entity("Persistance.Database.Models.Menu", b =>
                {
                    b.Navigation("pizzas");
                });

            modelBuilder.Entity("Persistance.Database.Models.Pedido", b =>
                {
                    b.Navigation("detalles");
                });

            modelBuilder.Entity("Persistance.Database.Models.Variedad", b =>
                {
                    b.Navigation("ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
